### ISSUE TITLE
[Feature Request] Support Scala Native

### ISSUE THREAD

**Issue by lolgab** [endpoints4s/endpoints4s#1032]
It would be lovely if endpoints4s core would support Scala Native.

I would love to have an endpoint4s frontend for my [SNUnit](https://github.com/lolgab/snunit) Scala Native HTTP Server.

**Comment by julienrf** [comment]
Sure! We need to cross-build the algebra modules so that you can define an endpoints4s interpreter for SNUnit. Do you have an idea of what we’d need to do to do that? I have never cross-built to Scala Native.

**Comment by lolgab** [comment]
I had tried in the past without success because Scala Native missed Scala 3 artifacts and scala-java-time. Now it seems it was easy :)
Can you approve the CI workflow on the linked PR ?
