### ISSUE TITLE
Generating OpenApi fails for parametrized classes

### ISSUE THREAD

**Issue by freakybit** [endpoints4s/endpoints4s#1065]
`endpoints4s.openapi.EndpointsWithCustomErrors.openApi(...)` uses internally a hashmap to keep track of paths. This fails for parametrized classes.

Consider:
```
package bar
case class FooWrapper[A](foo: A)
```
If we have multiple responses like this, we will keep only the last one as `"$ref": "#/components/schemas/bar.FooWrapper"` and it will reference the last `A` value that we encountered.

We need to generate `"$ref": "#/components/schemas/bar.FooWrapperA"` path for each `A` value.

**Comment by julienrf** [comment]
I don’t think there is a cross-platform way to generate correct unique identifiers for polymorphic classes, this is why the provided implementation does use the JVM-erased name.

You can customize this by providing an implicit `GenericJsonSchema.GenericSchemaName[A]` with your own logic. For instance:

~~~ scala
import scala.reflect.runtime.universe.TypeTag

trait GenericJsonSchemasWithFullNames extends endpoints4s.generic.JsonSchemas {

  // Generates `bar.FooWrapper_Quux` for `FooWrapper[Quux]`
  implicit def genericSchemaNameFromTypeTag[A](implicit tag: TypeTag[A]): GenericJsonSchema.GenericSchemaName[A] = {
    val typeArguments       = tag.tpe.typeArgs
    val typeArgumentsSuffix = typeArguments.map(tpe => "_" + tpe.typeSymbol.fullName).mkString
    val jvmName             = tag.tpe.typeSymbol.fullName + typeArgumentsSuffix
    new GenericJsonSchema.GenericSchemaName(Some(jvmName))
  }

}
~~~

**Comment by freakybit** [comment]
Oh, great. That solves it. Thanks.
