### ISSUE TITLE
Akka license changes

### ISSUE THREAD

**Issue by ptrdom** [endpoints4s/endpoints4s#1103]
With Akka's move to BSL license and its ASF fork getting traction (https://github.com/apache/incubator-pekko), I think we should consider doing one of the following upon Pekko's release:
- Change all Akka-based code to use Pekko.
- Create Pekko-based alternatives for all Akka-based code.

**Comment by pjfanning** [comment]
Pekko HTTP 1.0.0 should be released this week.

https://pekko.apache.org/docs/pekko-http/current/

**Comment by julienrf** [comment]
I see in the stats that the Akka HTTP interpreter is still used by ~15% of the users of endpoints4s.

For the sake of simplicity, I would like to avoid having both Akka HTTP and Pekko HTTP in this repository (endpoints4s/endpoints4s). It would be better to move the existing Akka HTTP interpreter to its own repository (endpoints4s/akka-http) and have the Pekko HTTP interpreter here. Is there anyone interested in this task?

**Comment by ptrdom** [comment]
I was planning to pick this up eventually, and I think I should be able to get started even this week. Moving Akka HTTP to a separate repository and replacing it in this repository with Pekko certainly simplifies things. In regards to the new repository for Akka HTTP interpreter, I assume that because of permissions and secrets required for the initial repository setup, @julienrf you are the only person that can do that, am I correct?

**Comment by ptrdom** [comment]
@julienrf I pushed the initial split to https://github.com/endpoints4s/akka-http, but the branch was called `split` and it got set as default branch. Could you set `main` as default? I do not have the permissions to do that.

**Comment by julienrf** [comment]
Thank you very much @ptrdom! I changed the default branch to `main` and also gave you admin access to the repo in case this is needed in the future…
