### ISSUE TITLE
Tupler : (A, (B, C, D)) -> (A, B, C, D)

### ISSUE THREAD

**Issue by ant8e** [endpoints4s/endpoints4s#1160]
The case (A, (B, C, D)) -> (A, B, C, D) does not seem to be covered.

I stumbled on this on an endpoint who has one path parameter and three query parameters.
The tupler Out is  (A, (B, C, D)). When I add a fourth query parameter it gives me a more friendly (A, B, C, D E)

**Comment by julienrf** [comment]
See #1161. The approach does not really scale, but I hope inserting that rule is fine :)

**Comment by ant8e** [comment]
Thanks Julien
