### ISSUE TITLE
Issue with `algebra-testkit` and `algebra-circe-testkit` release version numbers in endpoints4s `1.11.0`

### ISSUE THREAD

**Issue by ptrdom** [endpoints4s/endpoints4s#1216]
Besides documentation failing to publish, I think we have an issue with version numbers - new `algebra-testkit` `algebra-circe-testkit` releases got published as `1.0.0` instead of `5.0.0`. @julienrf We need to fix this, right? In that case, how do we go about it?

**Comment by julienrf** [comment]
Indeed, good catch! The Scala 3 artifacts automatically got version 1.0.0 because there was no previous release before. I will re-publish them with the correct version.

**Comment by julienrf** [comment]
I’ve deployed the new documentation and re-published the testkit with their correct version number. @OlegYch, could you please let us know if the migration to Play 3 is still not possible?

**Comment by ptrdom** [comment]
Can we delete the incorrectly published `1.0.0` versions?

**Comment by OlegYch** [comment]
@julienrf it seems to work, but there is a test failure https://github.com/endpoints4s/play/actions/runs/7063164652/job/19228533971

**Comment by ptrdom** [comment]
> Unfortunately not, not on Maven Central

Ah, interesting. I see that the artifact is not in Maven Central yet at this moment, so maybe a delete from Sonatype before the sync happens would prevent the incorrectly published artifacts from ending up in Maven Central? IIRC I have deleted artifacts from Sonatype.

**Comment by julienrf** [comment]
Ah, ok, I didn’t know. How do we do that?
