### ISSUE TITLE
numeric JSON schemas don’t support a format (and other documentation attributes)

### ISSUE THREAD

**Issue by julienrf** [endpoints4s/endpoints4s#542]
According to the OpenAPI specification, it is possible to set attributes such as `format`, `minimum`, etc. to numeric JSON schemas:

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#schemaObject

We should provide a new `JsonSchema` constructor for each numeric type (`Int`, `Long`, `Double`, `Float`). These constructors should take as parameters the currently missing documentation attributes.

The default (implicit) `JsonSchema` for these types should not set these parameters. (Like we do with `stringJsonSchema`)

**Comment by bmeesters** [comment]
I am not sure if I am understanding you correctly. But the format determines the type right?

![image](https://user-images.githubusercontent.com/32057771/99643750-5e6d4580-2a4d-11eb-93c6-5ab064225875.png)

So each constructor has optional properties like `minimum`, `'maxiumum`, etc, and the type `Float`, `Double`, `Int`, `Long` determines the possible format (if any). I.e. you cannot use JsonSchema[Int] with format `float`.

WDYT?

**Comment by julienrf** [comment]
Indeed, `format` is already added to the schemas according to the OpenAPI Specification. I think we need only need to add support for the optional properties that can be attached to numeric schemas: https://json-schema.org/understanding-json-schema/reference/numeric.html.

**Comment by bmeesters** [comment]
Yes, sorry, I was a little ask the question again (so I deleted it), without properly looking at what was already there. I think I have a working solution. Though it needs some fine tuning to ensure it is backwards compatible. I'll make a draft PR so we can look at the solution.
