### ISSUE TITLE
Scala 3 support

### ISSUE THREAD

**Issue by julienrf** [endpoints4s/endpoints4s#566]
#559 shows that the project compiles with Dotty.

The next steps are:

- [x] compile all the modules with Scala 3
- [ ] run the tests with Dotty (requires scalatest to be published for recent Dotty versions)
- [ ] publish artifacts for Dotty (requires adding an sbt command to the `.travis.yml`)
- [x] migrate the `endpoints-json-schema-generic` module (should we use Shapeless 3? Magnolia? A vanilla Scala 3 solution?)

**Comment by stefanholzmueller** [comment]
According to https://github.com/scalatest/scalatest/issues/1865, scalatest 3.2.1 is published for Dotty 0.26.0-RC1 now. I quickly tried ` sbt "++ 0.25.0-RC2 -v compile"`, but it seems that circe does not support newer Dotty versions yet.

When I tried to run the tests, I even got some NullPointerExceptions from Dotty. I won't dig deeper today, I was just curious and wanted to share my results.

**Comment by harpocrates** [comment]
Dotty issue I opened for a NPE in json-schema's testsuite: https://github.com/lampepfl/dotty/issues/9572.

**Comment by MasseGuillaume** [comment]
@julienrf Coucou, what can I do to make this happen?

**Comment by GrafBlutwurst** [comment]
I would also be willing to chip into this effort. Lemme know if i can help somehow.

**Comment by julienrf** [comment]
Thank you for your messages!

All the code compiles with Scala 3, but the real blocker is the state of the module `json-schema-generic`. That module contains implementation details that need to be made `public` because of a limitation of Scala 3 (IIUC, see lampepfl/dotty#11706):

https://github.com/endpoints4s/endpoints4s/blob/6ab7db825c4e567e77d3a5abf669ad7829df9050/json-schema/json-schema-generic/src/main/scala-3/endpoints4s/generic/JsonSchemas.scala#L122

Furthermore, the current implementation of the macros produces code that gives warnings at compile-time: https://github.com/endpoints4s/endpoints4s/runs/5138703907?check_suite_focus=true#step:8:51

Based on the Sonatype stats, I believe the module `json-schema-generic` is used a lot, so I think it’s better to wait for this module to be ready before we publish Scala 3 artifacts (alternatively, we could publish the Scala 3 artifacts for all the other modules except `json-schema-generic`, but I don’t think it would be helpful since many people use `json-schema-generic`).

So, we need to fix that module for the Scala 3 support to be complete. Currently, we use an approach as documented [here](https://docs.scala-lang.org/scala3/reference/contextual/derivation.html), with just `inline` stuff, but we could try to follow what is explained [here](https://docs.scala-lang.org/scala3/reference/contextual/derivation-macro.html), with quoted code, to see if that solves the two aforementioned issues (the fact that some implementation details can’t be made `private`, and the fact that the code resulting from the inlining process produces warnings).

I don’t have much time to work on these items right now so I would appreciate any help!

**Comment by MasseGuillaume** [comment]
Great thanks for the pointers!

**Comment by GrafBlutwurst** [comment]
I started playing around with it yesterday and I think one of the issues we have is that in this signature

```
inline def summonRecord[
    Types <: Tuple,
    Labels <: Tuple,
    Docs <: Tuple,
    DefaultValues <: Tuple
  ](
```

scalac doesn't know that the arity for all this tuples has to be the same. I am trying to solve this particular issue by calculating a new taype `(Types_1, Labels_1, Docs_1, DefaultValues_1) *: ... *: (Types_n, Labels_n, Docs_n, DefaultValues_n)` but then i run into the issue that we don't actually have a value for that but rather only for `Docs` and `DocValues`. I also had trouble telling scalac that the individual tuples have homogenous upper bounds. I'll continue to bang my head against this, maybe i can come up with the necessary combinators in a reusable way because I image we'd have similar issues in other places.

If anyone knows more about the new Tuples and how to deal with them, has good resources or knows libraries that already implement such thing (either so we can use them or have a look at how other people solve this) I'd be greatful if you'd let me know.

**Comment by julienrf** [comment]
I’ve opened #1099 to tackle the remaining problems to fully address Scala 3 support.

I think we are quite close! There are still issues with the usage of the Akka streams graph DSL, and an issue with the json-schema-generic macros expansion causing an infinite loop at compile-time. I don’t have much time to look at those problems, please let me know here if you can help!

**Comment by julienrf** [comment]
@ptrdom pushed #1099 to the finish line. The ultimate task is to update the publish instructions to publish for Scala 3 only the modules that don’t have dependencies with `CrossVersion.for3Use2_13` (for those, we should publish only the 2.13 artifacts, and users of these modules will use `for3Use2_13`).
