### ISSUE TITLE
scala.js 1.X support

### ISSUE THREAD

**Issue by ngbinh** [endpoints4s/endpoints4s#572]
Hi, scala.js 0.6.X line is about to be discontinued. It would be great if `endpoints` support scala.js 1.X https://github.com/scala-js/scala-js/issues/4045

**Comment by julienrf** [comment]
I would like to get help on this one. I was planning to do the next release with 0.6.x support only, and then immediately after to update to 1.x and stop supporting 0.6.x. I’m happy to follow another path if someone is willing to make a PR.

What needs to be adapted is the `.travis.yml` command that publishes the artifacts. We need to make sure that we publish the right artifacts for the right Scala versions.

**Comment by ngbinh** [comment]
I can work on upgrading scala.js to 1 but probably not cross-build with both 0.6 and 1.0.

**Comment by julienrf** [comment]
Fixed by #582
