### ISSUE TITLE
New organization name

### ISSUE THREAD

**Issue by julienrf** [endpoints4s/endpoints4s#593]
As suggested on [gitter](https://gitter.im/julienrf/endpoints?at=5eb98a65fb95b64428d4bbc5), it could be interesting to move the current `endpoints` repository to a separate organization. I would like to use this opportunity to also change the organization name of the published artifacts (currently, we use `org.julienrf`).

I’m not very imaginative… I would like to ask you if you have ideas for an organization name. It could be `scala-endpoints` for the github organization, and `org.scala-endpoints` for the Maven organization.

**Comment by julienrf** [comment]
The organization name `endpoints4s` has also been proposed on gitter. Please vote for it by reacting with a :+1: on this comment.

**Comment by harpocrates** [comment]
> The organization name `endpoints4s` has also been proposed on gitter

I see the `4s` suffix on many library names (`json4s`, `http4s`, `avro4s`, ...). What does it signify?

**Comment by julienrf** [comment]
> I see the `4s` suffix on many library names (`json4s`, `http4s`, `avro4s`, ...). What does it signify?

AFAICT it means “for Scala”
