### ISSUE TITLE
Magnolia based JsonSchema derivation

### ISSUE THREAD

**Issue by Fristi** [endpoints4s/endpoints4s#606]
Shapeless tends to get slower.. for 2.12 and 2.13 when you add more instances

**Comment by julienrf** [comment]
Why not. More important to me is to have solution for generic derivation that is future-proof (ie, supports Scala 3). I’ve seen that shapeless has a version that supports Scala 3 (but with a different API than the current stable version of shapeless). It seems that there is some ongoing effort to support Scala 3 in Magnolia. I wonder if we could just reuse the built-in generic derivation system in Scala 3, without additional layer?

Also worth mentioning: https://github.com/scalalandio/endpoints-json-schemas-macros

**Comment by Fristi** [comment]
For projects being stuck at Scala 2 for abit, magnolia might be a reasonable alternative to Shapeless. While shapeless is an elegant solution with it's inductive solution, it tends to get slow with a lot of instances and the error messages are not helpful when a implicit cannot be resolved. Magnolia fixes that.

I've been puzzling a bit with this one, `JsonSchema` is not very concrete.. Derivation of other type classes are either done in terms of using `Applicative` (covariant type class)  or `Divisible` (contravariant type class) combinators, yet `JsonSchema` can be both (invariant). The solution based on shapeless works with `zip` and creates a heterogeneous product type. With the magnolia api, you just loop over the params and have the type class instance in scope. 

The magnolia derivation process is explained here: https://propensive.com/opensource/magnolia/tutorial

Could we add combinators which enables the derivation with magnolia you think?

**Comment by julienrf** [comment]
You mean we need to add new operations to the `algebra` module? What would be there signatures?
