### ISSUE TITLE
JSON schemas of objects containing optional properties with default values are not well supported

### ISSUE THREAD

**Issue by julienrf** [endpoints4s/endpoints4s#635]
It is common to evolve a schema by adding a new optional field for which we fallback to a default value if it is missing.

For instance, consider the following case class modeling a point:

~~~ scala
case class Point(latitude: Double, longitude: Double)
~~~

A corresponding JSON schema would be the following:

~~~ scala
val pointSchema: JsonSchema[Point] = (
  field[Double]("latitude") zip
  field[Double]("longitude")
).as[Point]
~~~

To evolve our data type to include the elevation above ground level (with a default value of `0`), in Scala we just add a field with a default value:

~~~ scala
case class Point(latitude: Double, longitude: Double, elevation: Double = 0)
~~~

A backward compatible JSON schema would have an optional `elevation` field. When the `elevation` is missing, we want to decode a `Point` with an elevation of `0`. Such a schema can be defined as follows:

~~~ scala
val pointSchema: JsonSchema[Point] = (
  field[Double]("latitude") zip
  field[Doubel]("longitude") zip
  optField[Double]("elevation").xmap(_.getOrElse(0))(Some(_))
).as[Point]
~~~

We might want to introduce a method for modeling a JSON schema with an optional field decoded to a default value:

~~~ scala
final def optFieldWithDefault[A: JsonSchema](name: String, defaultValue: A, docs: Option[String] = None): Record[A] =
  optField(name, docs).xmap(_.getOrElse(defaultValue))(Some(_))
~~~

So that the above snippet can be simplified to:

~~~ scala
val pointSchema: JsonSchema[Point] = (
  field[Double]("latitude") zip
  field[Doubel]("longitude") zip
  optFieldWithDefault[Double]("elevation", 0)
).as[Point]
~~~

Last, generic derivation could detect when a case class field has a default value and map it to an `optFieldWithDefault` in such a case. Libraries like Circe already derive such codecs.

**Comment by gmarti** [comment]
I don't like the optFieldWithDefault name
Because the field is not optional, it's required but has a default value

maybe fieldWithDefault ?

**Comment by julienrf** [comment]
The field is not optional in the case class, but it is optional in the JSON schema (if you omit it, it will be decoded as its default value).
