### ISSUE TITLE
Optional query string parameter with a default value

### ISSUE THREAD

**Issue by harpocrates** [endpoints4s/endpoints4s#660]
One thing that has come up at work several times: we'd like to be able to declare an optional query string parameter with a default value. OpenAPI supports describing default values (see "Default Parameter Values" on [this page](https://swagger.io/docs/specification/describing-parameters/)).

I've not given much thought to syntax for this, but ideally you could do something like this:

```scala
path / "api" / "v1" / "pets" /? qs[Int]("limit", default = 5): Url[Int]
```

Then, the endpoint would have a default value

  * server interpreters would look for an optional param and use the default value as a fallback
  * documentation interpreters would generate docs mentioning the default value (Swagger UI knows how to generate forms that fill this default in nicely, I think)
  * client interpreters would be generated always specifying the value (so never using the default)

---

As a workaround, we've been doing the following, but that forces us to put information about the default value in documentation, and the generated OpenAPI isn't as useful. 

```scala
path / "api" / "v1" / "pets" /? qs[Option[Int]]("limit").xmap(_.getOrElse(5))(Some(_)): Url[Int]
```

**Comment by harpocrates** [comment]
I'd be happy to implement this. I'll have to think a little about how this could fit into the `QueryStringParam`/`QueryString` types that get used first though.

**Comment by julienrf** [comment]
Interesting, actually I didn’t know we could document default values for optional parameters. I see that this is supported in JSON schemas as well.

Currently, we use your workround to implement JSON schemas of objects having an optional field with a default value:

https://github.com/endpoints4s/endpoints4s/blob/99a1a74ea852ddd85bf4a6fbd12b06063ee312a8/json-schema/json-schema/src/main/scala/endpoints4s/algebra/JsonSchemas.scala#L292-L309

But as you said, the generated documentation doen’t tell about the default value.

So, this discussion makes me think that we could try to have a homogeneous syntax for both JSON schemas and query string parameters.

Speaking of the syntax, adding an overload `qs[Int]("limit", default = 5)` should work.

**Comment by harpocrates** [comment]
Great point about aiming for a solution that deals with JSON schemas and query string parameters in the same way - I hadn't noticed that this was supported in JSON schema as well. It'll simplify some of the boilerplate docs we currently include (which do little more than comment about what the default value of the optional field it). Unless someone beats me to it, I'll make a PR as soon as I have some time (hopefully later this week).On Oct 22, 2020, at 2:30 AM, Julien Richard-Foy <notifications@github.com> wrote:Interesting, actually I didn’t know we could document default values for optional parameters. I see that this is supported in JSON schemas as well.Currently, we use your workround to implement JSON schemas of objects having an optional field with a default value:https://github.com/endpoints4s/endpoints4s/blob/99a1a74ea852ddd85bf4a6fbd12b06063ee312a8/json-schema/json-schema/src/main/scala/endpoints4s/algebra/JsonSchemas.scala#L292-L309But as you said, the generated documentation doen’t tell about the default value.So, this discussion makes me think that we could try to have a homogeneous syntax for both JSON schemas and query string parameters.Speaking of the syntax, adding an overload qs[Int]("limit", default = 5) should work.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by julienrf** [comment]
I have a problem with the way default values are modeled in JSON schemas. Consider the case where you have an object type `Foo` containing an optional property of type `Bar` with a default value. We would put the information about the default value used by `Foo` in the schema of `Bar`:

~~~ javascript
{
  "Foo": {
    "type": "object",
    "properties": {
      "bar": { "$ref": "#/components/schemas/Bar" }
    }
  },
  "Bar": {
    "type": "object",
    "properties": { /* something */ },
    "default": { /* something */ }
  }
}
~~~

The problem is that if another type `Quux` has an optional field of type `Bar` with a default value **different** from the default value used by `Foo`, we can’t represent it because the default value is not attached to the schema that contains the optional property (`Foo` or `Quux`), but to the schema of the target type (`Bar`).

This may not be an issue in query parameters, though, because we don’t name these schemas, so there is no possible reuse. (Only schemas of JSON entities can be named)

**Comment by julienrf** [comment]
@harpocrates In case you are working on the support of optional query parameters with default values, you may be interested in [this commit](https://github.com/endpoints4s/endpoints4s/commit/20e77bf3f3f8663edb3c230a514eba4856174ad5), which adds the ability to produce a `default` property to the schemas generated by endpoints4s.

**Comment by Fristi** [comment]
> The problem is that if another type Quux has an optional field of type Bar with a default value different from the default value used by Foo, we can’t represent it because the default value is not attached to the schema that contains the optional property (Foo or Quux), but to the schema of the target type (Bar).

If you have a type `Quux` and it has a field with type `Bar` and `Quux` has default values defined, it would have a field with a default value for type `Bar`, would you still run in to the problem?

**Comment by julienrf** [comment]
> Because it needs to include all fields and therefore all the default values of the types it includes.

Except when we `$ref` to a schema. In that case, the referenced schema is shared, so no overriding is possible. If I understood correctly.

**Comment by Fristi** [comment]
I solved this problem also in an Avro library I've developed. Like with `JsonSchema` I came up with a abstract way of describing data structures like seen here: https://gist.github.com/Fristi/525d4381dc1c966a42abeb189f585d37#file-data-scala-L33 (this is simalair to the work of xenomorph and schemaz)

In the Avro library I created a few different type classes like `AvroEncoder` , `AvroDecoder` and also `AvroDefaultValuePrinter`. An sample of this can be seen here for JSON https://gist.github.com/Fristi/525d4381dc1c966a42abeb189f585d37#file-data-scala-L33 (where you supply a `Dsl[A]` value and get back a `JsonDecoder[A]`. Basically it interprets the high level dsl description into a type class. This is what xenomorph does (https://github.com/nuttycom/xenomorph)

In the `AvroDefaultValuePrinter` case you would make an type class like this

```scala
object AvroDefaultValuePrinter {

  import scala.collection.JavaConverters._

  def create[A](f: A => JsonNode): AvroDefaultValuePrinter[A] = new AvroDefaultValuePrinter[A] {
    override def print(value: A): JsonNode = f(value)
  }

  def by[A, B](printer: AvroDefaultValuePrinter[A])(f: B => A): AvroDefaultValuePrinter[B] = new AvroDefaultValuePrinter[B] {
    override def print(value: B): JsonNode = printer.print(f(value))
  }

  implicit val interpreter: AvroAlgebra[AvroDefaultValuePrinter] = new AvroAlgebra[AvroDefaultValuePrinter] with AvroDefaultValuePrinterRecordN {

    override val int: AvroDefaultValuePrinter[Int] = create(new IntNode(_))
    override val string: AvroDefaultValuePrinter[String] = create(new TextNode(_))
    override val bool: AvroDefaultValuePrinter[Boolean] = create(BooleanNode.valueOf)
    override val float: AvroDefaultValuePrinter[Float] = create(v => new DoubleNode(v.toDouble))

    override def bigDecimal(scale: Int, precision: Int): AvroDefaultValuePrinter[BigDecimal] = by(byteArray) { decimal =>
      val decimalType = LogicalTypes.decimal(precision, scale)
      val decimalConversion = new Conversions.DecimalConversion

      decimalConversion.toBytes(decimal.setScale(scale).bigDecimal, null, decimalType).array()
    }

    override val byteArray: AvroDefaultValuePrinter[Array[Byte]] =
      create(bytes => new TextNode(new String(bytes, Charset.forName("ISO-8859-1"))))

    override val double: AvroDefaultValuePrinter[Double] = create(new DoubleNode(_))

    override val long: AvroDefaultValuePrinter[Long] = create(new LongNode(_))

    override val cnil: AvroDefaultValuePrinter[CNil] = create(_ => NullNode.instance)

    override val uuid: AvroDefaultValuePrinter[UUID] = by(string)(_.toString)

    override val instant: AvroDefaultValuePrinter[Instant] = by(long)(_.toEpochMilli)

    override def option[A](from: AvroDefaultValuePrinter[A]): AvroDefaultValuePrinter[Option[A]] = create {
      case Some(v) => from.print(v)
      case None => NullNode.instance
    }

    override def list[A](of: AvroDefaultValuePrinter[A]): AvroDefaultValuePrinter[List[A]] =
      create(xs => new ArrayNode(JsonNodeFactory.instance).addAll(xs.map(of.print).asJava))

    override def set[A](of: AvroDefaultValuePrinter[A]): AvroDefaultValuePrinter[Set[A]] = by(list(of))(_.toList)

    override def vector[A](of: AvroDefaultValuePrinter[A]): AvroDefaultValuePrinter[Vector[A]] = by(list(of))(_.toList)

    override def seq[A](of: AvroDefaultValuePrinter[A]): AvroDefaultValuePrinter[Seq[A]] = by(list(of))(_.toList)
    
    override def map[K, V](value: AvroDefaultValuePrinter[V])(mapKey: String => Attempt[K])(contramapKey: K => String): AvroDefaultValuePrinter[Map[K, V]] = create { mm =>
      new ObjectNode(JsonNodeFactory.instance).putAll(mm.map { case (k, v) => contramapKey(k).trim -> value.print(v) }.asJava)
    }

    override def pmap[A, B](fa: AvroDefaultValuePrinter[A])(f: A => Attempt[B])(g: B => A): AvroDefaultValuePrinter[B] = by(fa)(g)

    override def imap[A, B](fa: AvroDefaultValuePrinter[A])(f: A => B)(g: B => A): AvroDefaultValuePrinter[B] = by(fa)(g)

    override def or[A, B](fa: AvroDefaultValuePrinter[A], fb: AvroDefaultValuePrinter[B]): AvroDefaultValuePrinter[Either[A, B]] = create {
      case Left(left) => fa.print(left)
      case Right(right) => fb.print(right)
    }
  }
}
```

Hope it makes sense! :)
