### ISSUE TITLE
Free monad interpreter

### ISSUE THREAD

**Issue by Krever** [endpoints4s/endpoints4s#68]
Although it may seem quite weird, we may want to have an interpreter that will convert api definition into ADT-based algebra that can be used in Free monad context.

The second point would be to find out if we can create some boilerplate that will allow to convert any client interpreter into Free interpreter. 

With this two functionalities we could sell the lib to the purest programmers :)

I have no personal interest in this feature at the moment but idea itself seems interesting to me.

**Comment by julienrf** [comment]
Yes, that could be useful :) It’s not going to be a free *monad* though (because requests and responses are dual and the free monad is not invertible), but we could indeed reify all the operations into an ADT. I’m not sure how we would handle extensibility, though.

**Comment by Krever** [comment]
Yeah, the extensibility would probably have to be abandoned  for come use cases, but if we just reify on the low level, it should be ok. 

Could you elaborate(or point to resources) on invertibility? Sounds interesting but I have no idea about this aspect of free monad or monads in general.

**Comment by julienrf** [comment]
This is indeed an interesting topic ^^

Invertible programming is the ability to generate dual programs like a parser and a pretty printer, or a decoder and an encoder, or a lens (which contains a get operation and an update operation), or … a client and a server (like we do in _endpoints_), from the same source code. You can find [here](https://hackage.haskell.org/package/invertible) some haskell typeclasses for invertible programming. You might already be familiar with some of them (like invariant functor).

About invertible monads: actually maybe there is some way to preserve invertibility with monads, according to [this blog post](https://mpilquist.github.io/blog/2015/06/18/invariant-shadows/).

**Comment by Krever** [comment]
Oh, now I get it. Originally I was thinking only about monad in scope of client code, as I couldn't see much sense with the server one.

**Comment by julienrf** [comment]
Closing since this is more an idea than an issue, and because it has been inactive for 4 years.
