### ISSUE TITLE
Generate Play client from Schema

### ISSUE THREAD

**Issue by marconilanna** [endpoints4s/endpoints4s#723]
The Akka HTTP client module supports both `JsonEntitiesFromCodecs` and `JsonEntitiesFromSchemas`. However, the Play client module only supports `JsonEntitiesFromCodecs`. A schema is required to generate OpenAPI documentation. So it is not possible to, at the same time, generate docs and a Play client?

**Comment by julienrf** [comment]
Good catch, this client interpreter is missing. Would you be interested in contributing it? It should be a low-hanging fruit, you can draw inspiration from the other interpreters.

**Comment by marconilanna** [comment]
@julienrf https://github.com/endpoints4s/endpoints4s/pull/724
