### ISSUE TITLE
Support any kind of recursive JSON schema

### ISSUE THREAD

**Issue by mleclercq** [endpoints4s/endpoints4s#834]
Existing support for recursive JSON schema only supports object schemas (with or without a discriminator field). It seems that it is not possible to write a JSON schema for an ADT like the following where `Expression.Literal` is represented as a JSON number and `Expression.Add` is represented as a JSON object:

```scala
sealed trait Expression
object Expression {
  case class Literal(value: Int) extends Expression
  case class Add(x: Expression, y: Expression) extends Expression
}
```

An example of a value would be:

```json
{"x": 1, "y": {"x": 2, "y": 3}}
```

That may sounds like a contrived example, but I do have an existing REST API that I would like to convert to endpoints4s that have constructs similar to this...

I prototyped two different approaches to tackle this:

1. generalize `lazyRecord` and `lazyTagged` with a new `lazySchema` method: 
   ```scala
   def lazySchema[A](schema: => JsonSchema[A], name: String): JsonSchema[A]
   ```
   It just so happen that both `lazyRecord` and `lazyTagged` can be implemented in term of `lazySchema` at very low cost (see https://github.com/mleclercq/endpoints/commit/c76f52a06726355cc3f89648d9e509002f964582)
2. add a new `recursiveSchema` method that works like a Y-combinator:
   ```scala
   def recursiveSchema[A](name: String)(f: JsonSchema[A] => JsonSchema[A]): JsonSchema[A]
   ```
   This approach requires a little bit more work especially in the openApi interpreter (see https://github.com/mleclercq/endpoints/commit/cc06cea55eac2db092e376fa6bd123b0607e8299)

With the first approach, the JSON schema for the `Expression` type above can be written as:

```scala
implicit val expressionSchema: JsonSchema[Expression] = {
  val self: JsonSchema[Expression] = lazySchema(expressionSchema, "Expression")
  intJsonSchema
    .orFallbackTo(field("x")(self) zip field("y")(self))
    .xmap[Expression] {
      case Left(value)   => Expression.Literal(value)
      case Right((x, y)) => Expression.Add(x, y)
    } {
      case Expression.Literal(value) => Left(value)
      case Expression.Add(x, y)      => Right((x, y))
    }
}
```

With the second approach, the JSON schema can be written as:

```scala
implicit val expressionSchema =
  recursiveSchema[Expression]("Expression") { implicit self =>
    intJsonSchema
      .orFallbackTo(field[Expression]("x") zip field[Expression]("y"))
      .xmap[Expression] {
        case Left(value)   => Expression.Literal(value)
        case Right((x, y)) => Expression.Add(x, y)
      } {
        case Expression.Literal(value) => Left(value)
        case Expression.Add(x, y)      => Right((x, y))
      }
  }
```

The second approach has the added benefit that it avoids the duplication of the type definitions in the generated OpenAPI.

For instance, given a simple endpoint defined as:

```scala
val eval = endpoint(
  post(path / "eval", jsonRequest[Expression]),
  ok(jsonResponse[Int])
)
```

The First approach gives the following (note that the JSON schema for `Expression` appears twice, in the `requestBody` and then in `components/schemas` as if the recursion was unfolded once):

```json
{
  "openapi": "3.0.0",
  "info": { "title": "My API", "version": "1.0.0" },
  "paths": {
    "/eval": {
      "post": {
        ...
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "oneOf": [
                  { "type": "integer", "format": "int32" },
                  {
                    "type": "object",
                    "properties": {
                      "x": { "$ref": "#/components/schemas/Expression" },
                      "y": { "$ref": "#/components/schemas/Expression" }
                    },
                    "required": ["x", "y"]
                  }
                ]
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Expression": {
        "oneOf": [
          { "type": "integer", "format": "int32" },
          {
            "type": "object",
            "properties": {
              "x": { "$ref": "#/components/schemas/Expression" },
              "y": { "$ref": "#/components/schemas/Expression" }
            },
            "required": ["x", "y"]
          }
        ]
      },
      "endpoints.Errors": { "type": "array", "items": { "type": "string" } }
    },
    "securitySchemes": {}
  }
}
```

While the second approach gives the following:

```json
{
  "openapi": "3.0.0",
  "info": { "title": "My API", "version": "1.0.0" },
  "paths": {
    "/eval": {
      "post": {
        ...
        "requestBody": {
          "content": {
            "application/json": {
              "schema": { "$ref": "#/components/schemas/Expression" }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Expression": {
        "oneOf": [
          { "type": "integer", "format": "int32" },
          {
            "type": "object",
            "properties": {
              "x": { "$ref": "#/components/schemas/Expression" },
              "y": { "$ref": "#/components/schemas/Expression" }
            },
            "required": ["x", "y"]
          }
        ]
      },
      "endpoints.Errors": { "type": "array", "items": { "type": "string" } }
    },
    "securitySchemes": {}
  }
}
```

**Comment by julienrf** [comment]
Thank you @mleclercq for the detailed description!

I like the elegance of the `recursiveSchema`, but does it work with several mutually recursive schemas?

Otherwise, I think it’s fine to add `lazySchema`. I think there was a discussion about it in the PR that introduced `lazyRecord` and `lazyTagged`, BTW.

**Comment by mleclercq** [comment]
> I like the elegance of the `recursiveSchema`, but does it work with several mutually recursive schemas?

Indeed, mutually recursive schemas could be problematic if you need to use both schemas in different endpoints since `recursiveSchema` return only one of them:

```scala
case class A(b: Option[B])
case class B(a: Option[A])
val aSchema = recursiveSchema[A]("A") { implicit a =>
  implicit val b = optField[A]("a").xmap(B.apply)(_.a)
  optField[B]("b").xmap(A.apply)(_.b)
}
```

A possible solution could be to make a more general version of `recursiveSchema` with a "side return value" (see https://github.com/mleclercq/endpoints/commit/8cfae77dd8b1c5d5d6360de0d992220b777341b1):

```scala
def recursiveSchemaF[A, B](name: String)(f: JsonSchema[A] => (JsonSchema[A], B)): (JsonSchema[A], B)

def recursiveSchema[A](name: String)(f: JsonSchema[A] => JsonSchema[A]): JsonSchema[A] =
  recursiveSchemaF[A, Unit](name)(s => f(s) -> ())._1
```

This way we can get both schemas out:

```scala
val (aSchema, bSchema) = recursiveSchemaF[A, JsonSchema[B]]("A") { implicit a =>
  implicit val b = optField[A]("a").xmap(B.apply)(_.a)
  optField[B]("b").xmap(A.apply)(_.b) -> b
}
```

The implementation of `recursiveSchemaF` for circe looks like:

```scala
def recursiveSchemaF[A, B](
    name: String
)(f: JsonSchema[A] => (JsonSchema[A], B)): (JsonSchema[A], B) = {
  object schema extends JsonSchema[A] {
    val (closedSchema, b) = f(this)
    val encoder: Encoder[A] = Encoder.instance(a => closedSchema.encoder(a))
    val decoder: Decoder[A] = Decoder.instance(c => closedSchema.decoder(c))
  }
  schema -> schema.b
}
```

It feels a bit weird to have the `schema` object to keep a reference `b` though...

Having that arbitrary side value improves the implementation of the openApi interpreter (no need to call `f` twice to get the `usjonSchema` and the `doc` which didn't feel right):

```scala
def recursiveSchemaF[A, B](
    name: String
)(f: JsonSchema[A] => (JsonSchema[A], B)): (JsonSchema[A], B) = {
  val (ujsonSchema, (doc, b)) =
    ujsonSchemas.recursiveSchemaF[A, (RecursiveSchema, B)](name) { s =>
      val (schema, b) = f(new JsonSchema(s, SchemaRef(name)))
      (schema.ujsonSchema, (RecursiveSchema(name, schema.docs), b))
    }
  new JsonSchema(ujsonSchema, doc) -> b
}
```

**Comment by julienrf** [comment]
Having both `recursiveSchema` and `recursiveSchemaF` (for power-users) would be fine to me, if we go with this approach.

I think the `lazySchema` is also quite simple to understand from the point of view of the end-users. It is not clear to me why this approach leads to duplicated schemas in the resulting OpenAPI document. Is this already the case in the current implementation?

Do you have a preference between both approaches (`lazySchema` vs `recursiveSchema`)?

**Comment by julienrf** [comment]
> The reason for that is that `lazySchema` (or `lazyRecord` and `lazyTagged`) are used as the recursive reference inside the schema. So in a schema like
> 
> ```scala
>   val recursiveSchema: Record[Recursive] = (
>     optField("next")(lazyRecord(recursiveSchema, "Rec"))
>   ).xmap(Recursive(_))(_.next)
> ```

Right, should we have an API like the following instead?

~~~ scala
val recursiveSchema: Record[Recursive] = lazyRecord("Rec") {
  optField("next")(recursiveSchema)
}.xmap(Recursive(_))(_.next)
~~~

**Comment by mleclercq** [comment]
That looks like the simplest solution! I'll give it a try

**Comment by mleclercq** [comment]
Indeed this solution works very well:

```scala
def lazySchema[A](name: String)(schema: => JsonSchema[A]): JsonSchema[A]

trait MyEndpoints extends algebra.Endpoints with algebra.JsonEntitiesFromSchemas {
  sealed trait Expression
  object Expression {
    case class Literal(value: Int) extends Expression
    case class Add(x: Expression, y: Expression) extends Expression
  }

  implicit val expressionSchema: JsonSchema[Expression] =
    lazySchema[Expression]("Expression") {
      intJsonSchema
        .orFallbackTo(field[Expression]("x") zip field[Expression]("y"))
        .xmap[Expression] {
          case Left(value)   => Expression.Literal(value)
          case Right((x, y)) => Expression.Add(x, y)
        } {
          case Expression.Literal(value) => Left(value)
          case Expression.Add(x, y)      => Right((x, y))
        }
    }

  val eval = endpoint(
    post(path / "eval", jsonRequest[Expression]),
    ok(jsonResponse[Int])
  )

  case class A(b: Option[B])
  case class B(a: Option[A])
  implicit val aSchema: JsonSchema[A] = lazySchema("A") {
    optField[B]("b").xmap(A.apply)(_.b)
  }
  implicit val bSchema: JsonSchema[B] = lazySchema("B") {
    optField[A]("a").xmap(B.apply)(_.a)
  }

  val a = endpoint(
    post(path / "a", jsonRequest[A]),
    ok(jsonResponse[Int])
  )
  val b = endpoint(
    post(path / "b", jsonRequest[B]),
    ok(jsonResponse[Int])
  )
}
```

See https://github.com/mleclercq/endpoints/commit/22801c46bbe7529d0e310ecdca654af8666dc28e

@julienrf, I can make it a PR if that works for you.

**Comment by julienrf** [comment]
Indeed, this looks nice! It would be great if you could open a PR :blush:

**Comment by mleclercq** [comment]
PR opened: https://github.com/endpoints4s/endpoints4s/pull/839
