### ISSUE TITLE
StreamedEntities

### ISSUE THREAD

**Issue by ptrdom** [endpoints4s/endpoints4s#944]
Initially discussed in https://github.com/endpoints4s/endpoints4s/pull/934.

Because of reframing done by browser for chunks transported with chunked transfer encoding, `ChunkedEntities` cannot be implemented for browser clients. Suggested fix would be to implement `StreamedEntities` API, which would be very similar to `ChunkedEntities`, but implemented through WebSockets.

**Comment by ptrdom** [comment]
Things to note in regards to how headers are handled with WebSockets:

- Response headers are not available. 
- Request headers are only available in clients that allow interaction with initial upgrade requests. 
  - Browsers do not allow it, but most server-side implementations should be good.
  - Browsers are known to pass cookies.

**Comment by julienrf** [comment]
If we want to use WebSockets under the hood, I wonder if we should introduce a more complete algebra (not limited to “streamed entities”), so that users could use the full power of WebSockets. I don’t have anything specific in mind, but I am just _a priori_ skeptical about the idea of hiding WebSockets as an implementation detail.

Also, I would like to support streaming for requests and responses in a way that is supported by all the existing client and server interpreters (Akka-http, http4s, web).

**Comment by ptrdom** [comment]
Hiding the implementation details does seem like a troublesome approach in case some better streaming implementation becomes available in the future. Also, richer interaction with the WebSocket makes sense at the very least for the functionality to explicitly close it. We could be more transparent about the use of WebSockets, for example by introducing `WebSocketEntities` with `webSocketEndpoint`. How does an approach like that sound?

**Comment by julienrf** [comment]
> Also, richer interaction with the WebSocket makes sense at the very least for the functionality to explicitly close it. We could be more transparent about the use of WebSockets, for example by introducing `WebSocketEntities` with `webSocketEndpoint`. How does an approach like that sound?

That makes sense, but I wonder if we can assume that the `WebSocket` protocol is well supported in the wild. Or maybe it is, but I believe we should still provide better support of the chunked transfer encoding, which is a simple way to perform streaming. I think the issue with the current implementation is that it assumes no reframing can happen, which is simply wrong. So, the solution seems to use explicit frame delimiters for formats that require that. Typically, we can stream binary files without worrying about reframing. We can even stream text content without worrying about reframing. We only need to introduce explicit frame delimiters to stream JSON data. https://en.wikipedia.org/wiki/JSON_streaming gives a couple of solutions used in the wild to stream JSON data.

**Comment by ptrdom** [comment]
>Send the JSON objects prefixed with their length and rely on a streaming parser to extract them.

I think this is the approach if we decide to go for a fix. It would be the most flexible because it does not put the responsibility on the transport implementation to pick a delimiter that will not collide with chunk contents. This is also how gRPC streaming is implemented. But still, XHR and Fetch do not currently have proper implementations in browsers to produce `ChunkedEntities` requests, if I remember correctly this is the reason why gRPC-web does not provide client side streaming.

Websockets are well supported though, client and server interpreters of endpoints4s definitely support them. Also, they are a good choice because of their intentional design for bidirectional streaming.

I kind of see that this could already be split into two issues - one for fixing up `ChunkedEntities`, other for potential implementation of WebSockets. Though I still think that efforts towards WebSocket implementation are worth the effort more than building the custom protocol for `ChunkedEntities`.

**Comment by julienrf** [comment]
> I think this is the approach if we decide to go for a fix. It would be the most flexible because it does not put the responsibility on the transport implementation to pick a delimiter that will not collide with chunk contents.

Awesome, let’s do that!

> But still, XHR and Fetch do not currently have proper implementations in browsers to produce `ChunkedEntities` requests, if I remember correctly this is the reason why gRPC-web does not provide client side streaming.

Assuming we would implement ourselves that small layer that decodes the messages (by reading the length prefix and than collecting all the chunks until the end of the message), I would expect Fetch could support efficient implementation of `ChunkedJsonEntities`?

> WebSockets are well supported though, client and server interpreters of endpoints4s definitely support them. Also, they are a good choice because of their intentional design for bidirectional streaming.

OK, then it’s probably a good thing to support them in endpoints4s. I think it would be important, as you mentioned, to support explicit `close`, so I am not sure we can do it with the same `Endpoint` type.

> I kind of see that this could already be split into two issues - one for fixing up `ChunkedEntities`, other for potential implementation of WebSockets.

💯

**Comment by ptrdom** [comment]
Continued in https://github.com/endpoints4s/endpoints4s/issues/953 and https://github.com/endpoints4s/endpoints4s/issues/954.
