### ISSUE TITLE
Client interpreter test compatibility with JVM and JS environments

### ISSUE THREAD

**Issue by ptrdom** [endpoints4s/endpoints4s#945]
Initially discussed in https://github.com/endpoints4s/endpoints4s/pull/934.

Current client interpreter test setup is not compatible with JS environment because of the use of dependencies which are incompatible with it. Suggested fixes:

1. Basing tests on `AsyncWordSpec` - current tests are based on synchronous `AnyWordSpec` and interact with async code through blocking - this is not supported in JS environment.
2. Producing stubs with Akka-HTTP server - current tests run WireMock instances and produce stubs from within the test implementations - this cannot be done in JS environment. WireMock could be ran through Docker before starting tests, with stubs prepared through configuration, but WireMock has limited stubbing support for `ChunkedEntities` and WebSockets - which will be needed for future https://github.com/endpoints4s/endpoints4s/issues/944. Starting an actual HTTP server in a similar manner - before starting tests and with stubs prepared through its implementation - seems like the best idea.

**Comment by ptrdom** [comment]
@julienrf Does the suggested implementation seem fine to you? I would proceed with this before continuing with either https://github.com/endpoints4s/endpoints4s/issues/953 or https://github.com/endpoints4s/endpoints4s/issues/954.

**Comment by julienrf** [comment]
Thank you for writing this up, yes, that seems to be the way to go! Thank you also for offering your help 😄
