### ISSUE TITLE
Protocol improvements for ChunkedEntities

### ISSUE THREAD

**Issue by ptrdom** [endpoints4s/endpoints4s#953]
Initially discussed in https://github.com/endpoints4s/endpoints4s/issues/944.

Because of reframing done by browsers upon the consumption of chunked encoding chunks, a chunk cannot be used as delimiting boundary of a stream element. Most flexible fix seems to be an implementation that sends stream elements prefixed by their length.

**Comment by ptrdom** [comment]
More generic solution to chunk delimiting problem would be to introduce a new delimiter algebra to clearly express the issue. For example, current implementation could be called a `chunkDelimiter`, because each stream element is put in its own chunk, and browsers would not implement this algebra. But then there could be `lengthPrefixDelimiter` - this one is described the issue description - or a `newLineDelimiter` and so on, and browsers would be able to implement these, and in turn implement the endpoints using them. 

Also, to accommodate the limitations of browsers - inability to send chunked requests - `ChunkedEntities` should have separate algebras for requests and responses.

@julienrf What do you think about these suggestions?

**Comment by ptrdom** [comment]
Though _delimiter_ may not be the most ideal term, maybe something like `chunksEncoder`/`chunksDecoder` makes more sense.

**Comment by julienrf** [comment]
I might be wrong but I think we could leave `byteChunks` and `textChunks` constructors as they are, and document that interpreters must not assume a 1:1 correspondence between chunks sent by a party and chunks received by another party (ie, reframing can happen).

This is why I think only `ChunkedJsonEntities` needs to be fixed. I am fine with introducing a concept of delimiter in the algebra, but we should double-check what are the current practices in the wild. I have seen that `circe-fs2` supports `'\n'` delimited JSON objects, so that’s good. What about OpenAPI? Is there a way to document how “stream items” are delimited? We could check AsyncAPI as well.

Does that make sense?

**Comment by ptrdom** [comment]
> I might be wrong but I think we could leave `byteChunks` and `textChunks` constructors as they are, and document that interpreters must not assume a 1:1 correspondence between chunks sent by a party and chunks received by another party (ie, reframing can happen).

I think I understand your point now, and I do agree. It is not necessary for the library to provide these, users can do it themselves if they need it. In addition to documentation, we should also alter the tests so that browser interpreters can implement `byteChunks` and `textChunks`.

> This is why I think only `ChunkedJsonEntities` needs to be fixed. I am fine with introducing a concept of delimiter in the algebra, but we should double-check what are the current practices in the wild. I have seen that `circe-fs2` supports `'\n'` delimited JSON objects, so that’s good. What about OpenAPI? Is there a way to document how “stream items” are delimited? We could check AsyncAPI as well.

I know Akka documentation indicates at least three ways of what they call _framing_ for JSON - very large arrays `[{"id": 1}, {"id": 2}, [...], {"id": 999}]`, comma delimited objects `{"id": 1}, {"id": 2}, [...], {"id": 999}` and newline delimited objects. 
It does not seem that OpenAPI implements this - there are some mentions of `spaceDelimited`, `pipeDelimited` and `collectionFormat`, but these are not used for response contents.
AsyncAPI seems to have gone back and forth with streaming. Older version had https://github.com/asyncapi/spec/blob/1.2.0/README.md#streamObject, which is very similar to what we are talking about. Then they dropped this approach in favor of channels https://github.com/asyncapi/spec/pull/184 and now there is https://github.com/asyncapi/spec/blob/master/examples/gitter-streaming.yml.

I guess that just like with the `byteChunks` and `textChunks` we do not have to introduce delimiter algebra, we could just pick one implementation and leave it to users of the library to implement whatever more they need themselves. What do you think would be the way to go?

**Comment by ptrdom** [comment]
Just to clarify, I still think that having delimiter (chunk codec) algebra for `ChunkedJsonEntities` is the way to go.

**Comment by julienrf** [comment]
> AsyncAPI seems to have gone back and forth with streaming. Older version had https://github.com/asyncapi/spec/blob/1.2.0/README.md#streamObject, which is very similar to what we are talking about. Then they dropped this approach in favor of channels [asyncapi/spec#184](https://github.com/asyncapi/spec/pull/184) and now there is https://github.com/asyncapi/spec/blob/master/examples/gitter-streaming.yml.

It is not clear to me how are “frames” delimited in an HTTP channel, by reading the documentation. Where is this explained?

**Comment by ptrdom** [comment]
It is not clear to me either, I shared all the links I found - docs are a bit dry on this. Also the `Trailer` header is used in a way that breaks the spec https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Trailer. It looks like this just was not though out thoroughly enough.

**Comment by ptrdom** [comment]
What I understood is that https://github.com/asyncapi/spec/blob/master/examples/gitter-streaming.yml#L159-L164 describes a free-form mapping for messages, so from the looks of it the implementation would just use the `Trailer` header value as frame delimiter.
