### ISSUE TITLE
Http4s client chunked requests do not work

### ISSUE THREAD

**Issue by ptrdom** [endpoints4s/endpoints4s#958]
Noticed while working on https://github.com/endpoints4s/endpoints4s/issues/945.

Likely remained unnoticed because the test implementation discards the failing assertion:
https://github.com/endpoints4s/endpoints4s/blob/19f893087c0f8f9060f14e79e3925b4030dba738/algebras/algebra/src/test/scala/endpoints4s/algebra/client/ChunkedJsonEntitiesTestSuite.scala#L180
With `callStreamedEndpoint(uploadEndpointTest, Source(expectedItems)).futureValue` the test starts failing.

**Comment by julienrf** [comment]
Thank you for reporting! I think the problem comes from the fact that the tests assume that no reframing can happen…

**Comment by ptrdom** [comment]
This one is actually an issue of JVM clients 😞 
Akka HTTP client fails with `org.scalatest.exceptions.TestFailedException: Vector(Array(1, 2, 3), Array(4, 5, 6)) did not equal List(Array(1, 2, 3), Array(4, 5, 6))`.
Http4s JVM client fails with `org.scalatest.exceptions.TestFailedException: Vector(Array()) did not equal List(Array(1, 2, 3), Array(4, 5, 6))`.
While I already fixed the assertion while working on https://github.com/endpoints4s/endpoints4s/issues/945, Http4s issue remains. I am not very familiar with the library.

**Comment by julienrf** [comment]
To be honest, it might be that http4s can’t support the endpoints4s way of streaming entities. If this is the case, we should remove the `ChunkedEntities` interpreters. Maybe @GrafBlutwurst can help?

**Comment by GrafBlutwurst** [comment]
@ptrdom do you have a branch i can replicate this on locally? I was looking for a case like this as it was one of the open discussion points. I was unable to replicate this myself though.

**Comment by ptrdom** [comment]
@GrafBlutwurst The issue can be replicated by modifying the last test in `endpoints4s.algebra.client.ChunkedJsonEntitiesTestSuite` to the following implementation:
```scala
"Encode chunks uploaded to a server" in {

  val expectedItems = List(Array[Byte](1, 2, 3), Array[Byte](4, 5, 6))

  serving(
    (post & path("upload")) {
      extractRequestEntity { entity =>
        onSuccess(entity.dataBytes.map(_.toArray).runWith[Future[Seq[Array[Byte]]]](Sink.seq)) {
          receivedItems =>
            receivedItems should contain theSameElementsAs expectedItems
            complete(HttpEntity.Empty)
        }
      }
    }
  ) {
    callStreamedEndpoint(uploadEndpointTest, Source(expectedItems)).futureValue
    ()
  }
}
```
Let me know if you still have issues replicating it locally, I will create a branch then.

**Comment by GrafBlutwurst** [comment]
In the http4s client chunked entities implementation put this:

```
  override def bytesChunksRequest
      : (Chunks[Array[Byte]], Http4sRequest[Effect]) => Http4sRequest[Effect] =
    (stream, req) =>
      req.withEntity(
        stream.flatMap(arr => fs2.Stream.chunk(Chunk.array(arr)))
      )
```

we used `req.withBodyStream` which does not adjust the headers. So `Transfer-Encoding: Chunked` was missing which caused the server to not read the full request. 

This is the entity encoder of https4s for streams which adds the header

```
/** A stream encoder is intended for streaming, and does not calculate its
    * bodies in advance.  As such, it does not calculate the Content-Length in
    * advance.  This is for use with chunked transfer encoding.
    */
  implicit def streamEncoder[F[_], A](implicit
      W: EntityEncoder[F, A]): EntityEncoder[F, Stream[F, A]] =
    new EntityEncoder[F, Stream[F, A]] {
      override def toEntity(a: Stream[F, A]): Entity[F] =
        Entity(a.flatMap(W.toEntity(_).body))

      override def headers: Headers =
        W.headers.get[`Transfer-Encoding`] match {
          case Some(transferCoding) if transferCoding.hasChunked =>
            W.headers
          case _ =>
            W.headers.add(`Transfer-Encoding`(TransferCoding.chunked.pure[NonEmptyList]))
        }
    }
    ```

**Comment by ptrdom** [comment]
@GrafBlutwurst No worries, I would see this as more of an issue with the faulty assertion in common test suite, either way bugs like these do happen 🤷‍♂️ With the merge of https://github.com/endpoints4s/endpoints4s/pull/959 the situation with tests, at least the client ones, should improve somewhat.

So the fix is basically the following, right?
```scala
override def bytesChunksRequest
      : (Chunks[Array[Byte]], Http4sRequest[Effect]) => Http4sRequest[Effect] =
    (stream, req) => req.withEntity(stream)
```

Would you like to create the PR? I could also handle it in case you are busy.

**Comment by GrafBlutwurst** [comment]
I'm a bit busy right now. If you could do it I would be very greatful, thanks!
