### ISSUE TITLE
Aborting requests in Scala.js client interpreters

### ISSUE THREAD

**Issue by ptrdom** [endpoints4s/endpoints4s#977]
While testing out `ChunkedJsonEntities` with Fetch I noticed that closing the response `ReadableStream` does not close its request. Having best front-end development practices for cleaning up opened resources in mind, endpoint4s should expose `abort` callbacks of both XHR and Fetch, ideally for any kind of endpoint.

References:
https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/abort
https://developer.mozilla.org/en-US/docs/Web/API/AbortController/abort

**Comment by julienrf** [comment]
Closed by #979
