### ISSUE TITLE
Kafka Topic algebra

### ISSUE THREAD

**Issue by ptrdom** [endpoints4s/endpoints4s#986]
I guess this is the last bit of critical functionality missing in endpoints4s when compared to Lagom Service Descriptors - https://www.lagomframework.com/documentation/1.6.x/scala/MessageBrokerApi.html. The algebra in itself would be rather simple - there are not to many moving parts in it, but unlike WebSockets, it could be argued that such algebra would be out of scope for this library if the focus is on HTTP APIs.

Thoughts?

**Comment by julienrf** [comment]
What we do in my current company is to use JSON schemas to define the format of the messages exchanged over Kafka. I guess what remains to do is to define an algebra around the concepts of topics, which servers want to publish to, and which clients want to subscribe to?

**Comment by ptrdom** [comment]
Yes, it is basically that. As I understand, there are only two components needed at algebra level for Kafka topics - topic name and message entity/type, everything else is specific to either the client or the server. It would probably make sense to eventually integrate AsyncAPI documentation.

**Comment by ptrdom** [comment]
@julienrf Just to confirm, you do think that such algebra would be in scope for endpoints4s?

**Comment by julienrf** [comment]
Actually, I think it could be a separate module, maybe even outside of the endpoints4s repo. To be honest, I am currently trying to move some modules of this repo outside of the repo, to ease the maintenance.

We should also create a page in the website to list all the "community" modules.

**Comment by ptrdom** [comment]
Great ideas! If JSON schemas were moved outside (documentation even mentions that they are dependency free), then these topics4s (😄) could definitely make use of them.

**Comment by ptrdom** [comment]
🤦‍♂️ JSON schemas artifacts _are_ actually published, so nothing is really blocking creation of this topic algebra module. I will just close this issue then.
